import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { TaskRepository } from '../src/server/storage/taskRepository';
import { reviewVersion, ReviewConflict } from '../src/server/services/reviewVersion';
import { claimReviewAction } from '../src/server/services/reviewActionGuard';
import { TaskLogService } from '../src/server/services/taskLogService';
import { DesignTaskLog } from '../src/types/tasks';
const originalCwd=process.cwd();
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'review-cas-'));
const db=path.join(dir,'tasks.sqlite');
TaskRepository.init(db);
try {
 const make=(id:string):DesignTaskLog=>({id,counter:1,source:'DESIGNER',suffix:'D',status:'AWAITING_TM_REVIEW',checkpoint:'TM_REVIEW',receivedAt:new Date().toISOString(),payload:{},events:[],hasError:false,listingResult:{en:{title:id}}});
 TaskRepository.createTask(make('A'));TaskRepository.createTask(make('B'));
 const original=TaskRepository.getTaskById('A')!;
 const version=reviewVersion(original);
 const context={taskId:'A',version};
 assert.throws(()=>claimReviewAction('B','submit-tm-review',context),ReviewConflict);
 assert.throws(()=>claimReviewAction('A','submit-tm-review',undefined),ReviewConflict);
 assert.throws(()=>claimReviewAction('A','submit-design-review',context),ReviewConflict);
 assert.equal(reviewVersion(TaskRepository.getTaskById('A')!),version);
 TaskRepository.addEvent('A',{timestamp:new Date().toISOString(),type:'TASK_HANDOFF',title:'log',content:{}});
 assert.equal(reviewVersion(TaskRepository.getTaskById('A')!),version,'logs preserve legacy token');
 const release=claimReviewAction('A','submit-tm-review',context);
 assert.throws(()=>claimReviewAction('A','submit-tm-review',context),ReviewConflict);
 const claimed=reviewVersion(TaskRepository.getTaskById('A')!);
 assert.notEqual(claimed,version);
 assert.throws(()=>claimReviewAction('A','submit-tm-review',{taskId:'A',version:claimed}),ReviewConflict,'busy even with current token');
 release();
 TaskRepository.close();TaskRepository.init(db);
 assert.throws(()=>claimReviewAction('A','submit-tm-review',context),ReviewConflict,'token consumed across restart');
 TaskRepository.updateTask('A',{listingResult:{en:{title:'Changed'}}});
 assert.notEqual(reviewVersion(TaskRepository.getTaskById('A')!),claimed);
 assert.equal(TaskRepository.getTaskById('B')!.listingResult.en.title,'B');
 assert.throws(()=>TaskRepository.updateTask('A',{id:'B'}),ReviewConflict);
 const fresh=TaskRepository.getTaskById('A')!;
 TaskRepository.updateTask('A',{updatedAt:new Date().toISOString()});
 assert.equal(reviewVersion(TaskRepository.getTaskById('A')!),reviewVersion(fresh));
 // A scan uses the in-flight guard but does not invalidate the editable listing.
 const scanVersion=reviewVersion(TaskRepository.getTaskById('A')!);
 const finishScan=claimReviewAction('A','submit-tm-review',{taskId:'A',version:scanVersion},'RECHECK');
 TaskRepository.updateTask('A',{trademarkWorkflowState:{phase:'SCANNING'}} as any);
 assert.equal(reviewVersion(TaskRepository.getTaskById('A')!),scanVersion);
 finishScan();
 const start=performance.now();
 for(let i=0;i<100;i++){const v=reviewVersion(TaskRepository.getTaskById('A')!);claimReviewAction('A','submit-tm-review',{taskId:'A',version:v})();}
 console.log(`PASS SQLite ownership, legacy initialization, CAS, duplicate/concurrent claims, restart, log stability; 100 claims ${(performance.now()-start).toFixed(1)} ms`);
 process.chdir(dir);
 const designs=path.join(dir,'data','designs');fs.mkdirSync(designs,{recursive:true});
 fs.writeFileSync(path.join(designs,'A_original.svg'),'<svg>original A</svg>');
 TaskRepository.updateTask('A',{status:'AWAITING_SVG_REVIEW',checkpoint:'SVG_REVIEW',svgContent:'<svg>edited A</svg>'});
 const beforeB=TaskRepository.getTaskById('B');
 const svgVersion=reviewVersion(TaskRepository.getTaskById('A')!);
 const finishReset=claimReviewAction('A','reset-svg',{taskId:'A',version:svgVersion});
 await TaskLogService.resetSvg('A');finishReset();
 assert.equal(TaskRepository.getTaskById('A')!.svgContent,'<svg>original A</svg>');
 assert.deepEqual(TaskRepository.getTaskById('B'),beforeB);
 console.log('PASS SVG reset persists only its owner task');
} finally {process.chdir(originalCwd);TaskRepository.close();fs.rmSync(dir,{recursive:true,force:true});}
